//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.22 at 10:39:03 PM IST 
//


package com.parkinglot.vehicles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.parkinglot.vehicles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.parkinglot.vehicles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllVehiclesRequest }
     * 
     */
    public GetAllVehiclesRequest createGetAllVehiclesRequest() {
        return new GetAllVehiclesRequest();
    }

    /**
     * Create an instance of {@link GetVehicleDetailsByIdResponse }
     * 
     */
    public GetVehicleDetailsByIdResponse createGetVehicleDetailsByIdResponse() {
        return new GetVehicleDetailsByIdResponse();
    }

    /**
     * Create an instance of {@link VehicleDetails }
     * 
     */
    public VehicleDetails createVehicleDetails() {
        return new VehicleDetails();
    }

    /**
     * Create an instance of {@link GetVehicleDetailsByIdRequest }
     * 
     */
    public GetVehicleDetailsByIdRequest createGetVehicleDetailsByIdRequest() {
        return new GetVehicleDetailsByIdRequest();
    }

    /**
     * Create an instance of {@link GetAllVehiclesResponse }
     * 
     */
    public GetAllVehiclesResponse createGetAllVehiclesResponse() {
        return new GetAllVehiclesResponse();
    }

    /**
     * Create an instance of {@link DeleteVehicleRequest }
     * 
     */
    public DeleteVehicleRequest createDeleteVehicleRequest() {
        return new DeleteVehicleRequest();
    }

    /**
     * Create an instance of {@link AddVehicleRequest }
     * 
     */
    public AddVehicleRequest createAddVehicleRequest() {
        return new AddVehicleRequest();
    }

    /**
     * Create an instance of {@link UpdateVehicleRequest }
     * 
     */
    public UpdateVehicleRequest createUpdateVehicleRequest() {
        return new UpdateVehicleRequest();
    }

    /**
     * Create an instance of {@link GetVehicleDetailsByLicenseResponse }
     * 
     */
    public GetVehicleDetailsByLicenseResponse createGetVehicleDetailsByLicenseResponse() {
        return new GetVehicleDetailsByLicenseResponse();
    }

    /**
     * Create an instance of {@link VehicleDetailsByLicense }
     * 
     */
    public VehicleDetailsByLicense createVehicleDetailsByLicense() {
        return new VehicleDetailsByLicense();
    }

    /**
     * Create an instance of {@link AddVehicleResponse }
     * 
     */
    public AddVehicleResponse createAddVehicleResponse() {
        return new AddVehicleResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link DeleteVehicleResponse }
     * 
     */
    public DeleteVehicleResponse createDeleteVehicleResponse() {
        return new DeleteVehicleResponse();
    }

    /**
     * Create an instance of {@link GetVehicleDetailsByLicenseRequest }
     * 
     */
    public GetVehicleDetailsByLicenseRequest createGetVehicleDetailsByLicenseRequest() {
        return new GetVehicleDetailsByLicenseRequest();
    }

    /**
     * Create an instance of {@link UpdateVehicleResponse }
     * 
     */
    public UpdateVehicleResponse createUpdateVehicleResponse() {
        return new UpdateVehicleResponse();
    }

}
